# Listen on port 1883 
listener 1883 0.0.0.0

# Allow clients to connect without a username / password 
allow_anonymous true

# keep the data if the container restarts 
persistence true
persistence_location /mosquitto/data
